"""
ODR router — generates the MSME ODR filing pack PDF.
Design matches the Bakaya sample output (two-column parties, claim table,
orange accents, escalation audit trail, document checklist).
"""
import io
from datetime import date
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from fpdf import FPDF
from sqlalchemy import select
from sqlalchemy.orm import Session

from ..database import get_db
from ..models import Buyer, Invoice, EscalationEvent
from ..rules import calculate_interest, _effective_due, STATUTORY_RATE, RBI_BANK_RATE

router = APIRouter(prefix="/api", tags=["odr"])

# ── colour palette ────────────────────────────────────────────────────────────
ORANGE   = (211, 84,  0)
NAVY     = (13,  43, 84)
MID_GRAY = (110, 110, 110)
LIGHT    = (245, 245, 245)
DARK     = (30,  30,  30)
WHITE    = (255, 255, 255)

STAGE_LABEL = {
    "nudge":          "Due -15",
    "tax_nudge":      "Due +1",
    "formal_demand":  "Due +30",
    "odr_ready":      "Due +45",
}
STAGE_DESC = {
    "nudge":          "Relationship-safe reminder issued",
    "tax_nudge":      "Section 43B(h) tax-deductibility notice issued",
    "formal_demand":  "Formal demand for principal + statutory interest",
    "odr_ready":      "ODR preparation - filing pack generated",
}


def _priority(days_overdue: int) -> str:
    if days_overdue >= 60:
        return "HIGH"
    if days_overdue >= 30:
        return "MEDIUM"
    return "LOW"


# ── PDF class ─────────────────────────────────────────────────────────────────
class OdrPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(18, 18, 18)

    def _hline(self, y=None, color=None):
        """Draw a full-width horizontal rule."""
        if y is None:
            y = self.get_y()
        if color is None:
            color = (210, 210, 210)
        self.set_draw_color(*color)
        self.line(self.l_margin, y, 210 - self.r_margin, y)
        self.set_draw_color(0, 0, 0)

    def odr_header(self, inv_number: str, val_date: str):
        """Top block: title, ref, valuation date, orange rule."""
        # Title + subtitle on the left
        self.set_font("Helvetica", "B", 22)
        self.set_text_color(*NAVY)
        self.set_xy(18, 16)
        self.cell(120, 10, "ODR FILING PACK")

        # REF + date on the right
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*ORANGE)
        self.set_xy(138, 16)
        self.cell(54, 5, f"REF: BKY/ODR/{inv_number}", align="R")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*MID_GRAY)
        self.set_xy(138, 21)
        self.cell(54, 5, f"Valuation date: {val_date}", align="R")

        # Subtitle
        self.set_font("Helvetica", "", 8.5)
        self.set_text_color(*MID_GRAY)
        self.set_xy(18, 27)
        self.cell(0, 5, "MSME Online Dispute Resolution  -  odr.msme.gov.in  |  Generated by Bakaya AI")

        # Orange rule
        self.set_draw_color(*ORANGE)
        self.set_line_width(0.8)
        self.line(18, 34, 192, 34)
        self.set_line_width(0.2)
        self.set_draw_color(0, 0, 0)
        self.set_y(38)

    def section_header(self, number: str, title: str):
        """Orange section title + gray underline."""
        self.ln(4)
        self.set_font("Helvetica", "B", 9.5)
        self.set_text_color(*ORANGE)
        self.cell(0, 6, f"{number}.  {title}", new_x="LMARGIN", new_y="NEXT")
        self._hline()
        self.ln(3)
        self.set_text_color(*DARK)

    def claim_row(self, label: str, value: str, bold_value=False, highlight=False):
        """Single label/value row. highlight=True draws the orange left bar."""
        y = self.get_y()
        row_h = 7

        if highlight:
            self.set_fill_color(*ORANGE)
            self.rect(self.l_margin, y, 2, row_h, "F")

        self.set_font("Helvetica", "", 8.5)
        self.set_text_color(*MID_GRAY)
        self.set_xy(self.l_margin + (4 if highlight else 0), y)
        self.cell(80, row_h, label)

        style = "B" if bold_value else ""
        self.set_font("Helvetica", style, 8.5 if not highlight else 9.5)
        self.set_text_color(*ORANGE if highlight else NAVY)
        self.cell(0, row_h, value, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*DARK)

        if highlight:
            self.ln(1)

    def checkbox(self, x: float, y: float, checked: bool):
        """Draw a small checkbox."""
        size = 3.5
        self.set_draw_color(*NAVY)
        self.set_line_width(0.3)
        if checked:
            self.set_fill_color(*NAVY)
            self.rect(x, y, size, size, "FD")
            # draw tick mark in white
            self.set_draw_color(*WHITE)
            self.set_line_width(0.6)
            self.line(x + 0.5, y + 2, x + 1.5, y + 3)
            self.line(x + 1.5, y + 3, x + 3, y + 1)
        else:
            self.set_fill_color(*WHITE)
            self.rect(x, y, size, size, "D")
        self.set_draw_color(0, 0, 0)
        self.set_line_width(0.2)


# ── route ─────────────────────────────────────────────────────────────────────
@router.get("/invoices/{id}/odr-pack")
def odr_pack(id: int, db: Session = Depends(get_db)):
    row = db.execute(
        select(Invoice, Buyer).join(Buyer).where(Invoice.id == id)
    ).first()
    if row is None:
        raise HTTPException(404, "Invoice not found")
    inv, buyer = row

    events = db.execute(
        select(EscalationEvent)
        .where(EscalationEvent.invoice_id == id)
        .order_by(EscalationEvent.sent_at)
    ).scalars().all()

    amount     = float(inv.amount)
    calc       = calculate_interest(amount, inv.invoice_date, inv.due_date)
    days_over  = calc["msmedDaysOverdue"]
    today      = date.today()
    val_date   = today.strftime("%d %B %Y")

    # Effective due date: min(agreed due, invoice + 45) per MSMED Act s.15
    from datetime import timedelta
    stat_due = _effective_due(inv.invoice_date, inv.due_date)

    months_over = days_over / 30
    interest_working = (
        f"{amount:,.0f} x (1 + {float(STATUTORY_RATE):.3f}/12) ^ "
        f"{months_over:.2f} - {amount:,.0f}"
    )

    pdf = OdrPDF()
    pdf.add_page()

    # ── HEADER ───────────────────────────────────────────────────────────────
    pdf.odr_header(inv.invoice_number, val_date)

    # ── 1. PARTIES ───────────────────────────────────────────────────────────
    pdf.section_header("1", "PARTIES")

    # two-column layout
    col_l = 18
    col_r = 110
    y_start = pdf.get_y()

    # left column header
    pdf.set_xy(col_l, y_start)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(*DARK)
    pdf.cell(80, 5, "CLAIMANT (Supplier)")

    # right column header
    pdf.set_xy(col_r, y_start)
    pdf.cell(0, 5, "RESPONDENT (Buyer)")
    pdf.ln(6)

    def party_line(left: str, right: str):
        y = pdf.get_y()
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(*DARK)
        pdf.set_xy(col_l, y)
        pdf.cell(88, 5, left)
        pdf.set_xy(col_r, y)
        pdf.cell(0, 5, right, new_x="LMARGIN", new_y="NEXT")

    party_line("MSME Supplier (Udyam-registered)", buyer.name)
    party_line(inv.invoice_date.strftime("Invoice date: %d %b %Y"),
               buyer.city or "")
    party_line("", f"GSTIN: {buyer.gst_number}" if buyer.gst_number else "")
    party_line("", "Buyer category: Large enterprise")

    # eligibility status in orange
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(*ORANGE)
    pdf.set_x(col_l)
    pdf.cell(0, 6, "Status: Udyam-registered  -  ELIGIBLE", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*DARK)
    pdf.ln(3)

    # ── 2. CLAIM ─────────────────────────────────────────────────────────────
    pdf.section_header("2", "CLAIM  -  INVOICE & STATUTORY INTEREST (MSMED Act 2006, s.16)")

    pdf.claim_row("Invoice no. / date",
                  f"{inv.invoice_number}  |  {inv.invoice_date.strftime('%d %b %Y')}")
    pdf.claim_row("Principal amount due",
                  f"Rs {amount:,.0f}", bold_value=True)
    pdf.claim_row("Effective due date (s.15)",
                  stat_due.strftime("%d %b %Y"), bold_value=True)
    pdf.claim_row("Days overdue (as of valuation)",
                  f"{days_over} days", bold_value=True)
    pdf.claim_row(f"Applicable rate (3 x RBI Bank Rate {float(RBI_BANK_RATE)*100:.2f}%)",
                  f"{float(STATUTORY_RATE)*100:.2f}% p.a.  -  compounded monthly", bold_value=True)
    pdf.claim_row("Interest workings", interest_working)
    pdf.claim_row("Interest accrued",
                  f"Rs {calc['totalInterest']:,.0f}", bold_value=True)

    # light separator before total
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.2)
    pdf.line(pdf.l_margin, pdf.get_y(), 192, pdf.get_y())
    pdf.ln(2)

    pdf.claim_row("TOTAL AMOUNT CLAIMED",
                  f"Rs {calc['totalDue']:,.0f}",
                  bold_value=True, highlight=True)
    pdf.ln(4)

    # ── 3. ESCALATION HISTORY ────────────────────────────────────────────────
    pdf.section_header("3", "ESCALATION HISTORY (audit trail)")

    if events:
        for ev in events:
            day_label = STAGE_LABEL.get(ev.stage, ev.stage.upper())
            description = STAGE_DESC.get(ev.stage, ev.stage)
            lang_note = f" ({ev.language})" if ev.language and ev.language.lower() not in ("en", "english") else ""
            y = pdf.get_y()

            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*DARK)
            pdf.set_xy(pdf.l_margin, y)
            pdf.cell(30, 6, ev.sent_at.strftime("%d %b %Y"))

            pdf.set_font("Helvetica", "B", 8.5)
            pdf.set_text_color(*ORANGE)
            pdf.set_xy(pdf.l_margin + 30, y)
            pdf.cell(20, 6, day_label)

            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*DARK)
            pdf.set_xy(pdf.l_margin + 50, y)
            pdf.cell(0, 6, description + lang_note, new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_font("Helvetica", "I", 8.5)
        pdf.set_text_color(*MID_GRAY)
        pdf.cell(0, 6, "No escalation events recorded yet.", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*DARK)

    pdf.ln(4)

    # ── 4. CLAIM STATEMENT ───────────────────────────────────────────────────
    pdf.section_header("4", "CLAIM STATEMENT")

    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*DARK)
    pdf.multi_cell(0, 5.5,
        f"The Claimant, a registered micro enterprise under the MSMED Act 2006, supplied goods "
        f"vide invoice {inv.invoice_number} dated {inv.invoice_date.strftime('%d %b %Y')} for "
        f"Rs {amount:,.0f}. Payment was not made within 45 days as required under s.15. "
        f"Under s.16, the Respondent ({buyer.name}) is liable to pay compound interest at three "
        f"times the RBI Bank Rate ({float(STATUTORY_RATE)*100:.1f}% p.a., compounded monthly). "
        f"Interest of Rs {calc['totalInterest']:,.0f} has accrued, making the total amount due "
        f"Rs {calc['totalDue']:,.0f}. The Claimant seeks recovery of the principal and accrued "
        f"interest, and refers the dispute to the MSE Facilitation Council under s.18 for "
        f"conciliation / arbitration."
    )
    pdf.ln(4)

    # ── 5. DOCUMENT CHECKLIST ────────────────────────────────────────────────
    pdf.section_header("5", "DOCUMENT CHECKLIST")

    checklist = [
        (True,         f"Tax invoice ({inv.invoice_number})"),
        (True,         "Purchase order / work order"),
        (True,         "Udyam Registration Certificate"),
        (False,        "Proof of delivery / acceptance"),
        (bool(events), "Payment reminder emails / escalation records"),
        (False,        "Bank statement showing non-receipt of payment"),
    ]

    col2_x = 18 + (192 - 18) / 2
    left_items  = checklist[::2]
    right_items = checklist[1::2]

    for i in range(max(len(left_items), len(right_items))):
        y = pdf.get_y()
        if i < len(left_items):
            checked, label = left_items[i]
            pdf.checkbox(18, y + 1, checked)
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*DARK)
            pdf.set_xy(24, y)
            pdf.cell(80, 6, label)
        if i < len(right_items):
            checked, label = right_items[i]
            pdf.checkbox(col2_x, y + 1, checked)
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*DARK)
            pdf.set_xy(col2_x + 6, y)
            pdf.cell(0, 6, label, new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.ln(6)

    # ── FOOTER DISCLAIMER ────────────────────────────────────────────────────
    pdf.ln(6)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(18, pdf.get_y(), 192, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(*MID_GRAY)
    pdf.multi_cell(0, 4.5,
        "Auto-generated by Bakaya AI from the invoice ledger and escalation audit trail. "
        "Figures computed deterministically (Decimal precision); interest rate is a configured "
        "statutory constant (3 x RBI Bank Rate), updated on RBI revision. "
        "Not legal advice - for filing assistance only."
    )

    buf = io.BytesIO(pdf.output())
    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="ODR-Pack-{inv.invoice_number}.pdf"'},
    )
